services:
  - type: web
    name: akshaya-backend
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port 10000
    envVars:
      - key: OPENAI_API_KEY
        sync: true
      - key: ELEVENLABS_API_KEY
        sync: true
      - key: GITHUB_TOKEN
        sync: true
      - key: GITHUB_USERNAME
        sync: true
      - key: FIREBASE_CREDS_PATH
        sync: true
      - key: RENDER_DEPLOY_HOOK
        sync: true
    autoDeploy: true
    plan: free
    region: oregon
    branch: main